"""Bundled Wikidata property metadata.

``PROPERTY_LABELS`` lets the client serve well-known PIDs (P36, P31, P17, ...)
in O(1) from this dict instead of round-tripping to the Wikidata REST API.
``DEFAULT_PROPERTIES`` is the curated list of PIDs the agent prefers when
expanding a subgraph.
"""

from __future__ import annotations

from typing import Dict, List

DEFAULT_PROPERTIES: List[str] = [
    "P31", "P279", "P27", "P361", "P527", "P495", "P17", "P585", "P106",
    "P569", "P570", "P577", "P50", "P571", "P641", "P625", "P19", "P69",
    "P108", "P136", "P39", "P161", "P20", "P101", "P179", "P175", "P7937",
    "P57", "P607", "P509", "P800", "P449", "P580", "P582", "P276", "P112",
    "P740", "P159", "P452", "P102", "P1142", "P1387", "P1576", "P140",
    "P178", "P287", "P25", "P22", "P40", "P185", "P802", "P1416", "P26",
    "P3373", "P451", "P1038", "P184", "P166", "P512", "P463", "P127",
    "P749", "P355", "P488", "P169", "P131", "P706", "P150", "P36", "P30",
    "P6", "P35", "P1313", "P54", "P1344", "P1532", "P170", "P86", "P162",
    "P58", "P144", "P921", "P407", "P264", "P1411", "P1082", "P2044",
    "P2046",
]


PROPERTY_LABELS: Dict[str, Dict[str, str]] = {
    "P6": {"label": "head of government", "description": "head of the executive power of this governmental body"},
    "P17": {"label": "country", "description": "sovereign state that this item is in"},
    "P19": {"label": "place of birth", "description": "most specific known birth location of a person"},
    "P20": {"label": "place of death", "description": "most specific known death location of a person"},
    "P22": {"label": "father", "description": "male parent of the subject"},
    "P25": {"label": "mother", "description": "female parent of the subject"},
    "P26": {"label": "spouse", "description": "the subject has the object as their spouse"},
    "P27": {"label": "country of citizenship", "description": "the object is a country that recognizes the subject as its citizen"},
    "P30": {"label": "continent", "description": "continent of which the subject is a part"},
    "P31": {"label": "instance of", "description": "that class of which this subject is a particular example and member"},
    "P35": {"label": "head of state", "description": "official with the highest formal authority in a country/state"},
    "P36": {"label": "capital", "description": "seat of government of a country, province, state or other administrative territorial entity"},
    "P39": {"label": "position held", "description": "subject currently or formerly holds the object position or public office"},
    "P40": {"label": "child", "description": "subject has object as child"},
    "P50": {"label": "author", "description": "main creator(s) of a written work"},
    "P54": {"label": "member of sports team", "description": "sports teams or clubs that the subject represents"},
    "P57": {"label": "director", "description": "director(s) of film, TV-series, stageplay, video game or similar"},
    "P58": {"label": "screenwriter", "description": "person(s) who wrote the script for subject item"},
    "P69": {"label": "educated at", "description": "educational institution attended by subject"},
    "P86": {"label": "composer", "description": "person(s) who wrote the music"},
    "P101": {"label": "field of work", "description": "specialization of a person or organization"},
    "P102": {"label": "member of political party", "description": "the political party of which a person is or has been a member"},
    "P106": {"label": "occupation", "description": "occupation of a person"},
    "P108": {"label": "employer", "description": "person or organization for which the subject works or worked"},
    "P112": {"label": "founded by", "description": "founder or co-founder of this organization, religion, place or entity"},
    "P127": {"label": "owned by", "description": "owner of the subject"},
    "P131": {"label": "located in the administrative territorial entity", "description": "the item is located on the territory of the following administrative entity"},
    "P136": {"label": "genre", "description": "creative work's genre or an artist's field of work"},
    "P140": {"label": "religion or worldview", "description": "religion of a person, organization or religious building"},
    "P144": {"label": "based on", "description": "the work(s) used as the basis for subject item"},
    "P150": {"label": "contains the administrative territorial entity", "description": "direct subdivisions of an administrative territorial entity"},
    "P159": {"label": "headquarters location", "description": "city or town where an organization's headquarters is situated"},
    "P161": {"label": "cast member", "description": "actor in the subject production"},
    "P162": {"label": "producer", "description": "person(s) who produced the film, musical work, theatrical production, etc."},
    "P166": {"label": "award received", "description": "award or recognition received by a person, organization or creative work"},
    "P169": {"label": "chief executive officer", "description": "highest-ranking corporate officer appointed as the CEO"},
    "P170": {"label": "creator", "description": "maker of this creative work or other object"},
    "P175": {"label": "performer", "description": "actor, musician, band or other performer associated with this work"},
    "P178": {"label": "developer", "description": "organization or person that developed the item"},
    "P179": {"label": "part of the series", "description": "series which contains the subject"},
    "P184": {"label": "doctoral advisor", "description": "person who supervised the doctorate or PhD thesis"},
    "P185": {"label": "doctoral student", "description": "doctoral student(s) of a professor"},
    "P264": {"label": "record label", "description": "brand and trademark for marketing of music recordings"},
    "P276": {"label": "location", "description": "location of the object, structure or event"},
    "P279": {"label": "subclass of", "description": "this subject is a subclass of that class"},
    "P287": {"label": "designed by", "description": "person or organization which designed the object"},
    "P355": {"label": "has subsidiary", "description": "child organization/unit of an organization/unit"},
    "P361": {"label": "part of", "description": "object of which the subject is a part"},
    "P407": {"label": "language of work or name", "description": "language associated with this creative work or a name"},
    "P449": {"label": "original broadcaster", "description": "network(s) that originally broadcast a radio or television program"},
    "P451": {"label": "unmarried partner", "description": "someone with whom the person is in a relationship without being married"},
    "P452": {"label": "industry", "description": "specific industry of company or organization"},
    "P463": {"label": "member of", "description": "organization, club or musical group to which the subject belongs"},
    "P488": {"label": "chairperson", "description": "presiding member of an organization, group or body"},
    "P495": {"label": "country of origin", "description": "country of origin of this item"},
    "P509": {"label": "cause of death", "description": "underlying or immediate cause of death"},
    "P512": {"label": "academic degree", "description": "academic degree that the person holds"},
    "P527": {"label": "has part(s)", "description": "part of this subject; inverse of 'part of' (P361)"},
    "P569": {"label": "date of birth", "description": "date on which the subject was born"},
    "P570": {"label": "date of death", "description": "date on which the subject died"},
    "P571": {"label": "inception", "description": "time when an entity begins to exist"},
    "P577": {"label": "publication date", "description": "date or point in time when a work was first published or released"},
    "P580": {"label": "start time", "description": "time an entity begins to exist or a statement starts being valid"},
    "P582": {"label": "end time", "description": "moment when an entity ceases to exist or a statement stops being valid"},
    "P585": {"label": "point in time", "description": "date something took place, existed or a statement was true"},
    "P607": {"label": "participated in conflict", "description": "battles, wars or other military engagements in which the subject participated"},
    "P625": {"label": "coordinate location", "description": "geocoordinates of the subject"},
    "P641": {"label": "sport", "description": "sport that the subject participates in or is associated with"},
    "P706": {"label": "located in/on physical feature", "description": "located on the specified geophysical feature"},
    "P740": {"label": "location of formation", "description": "location where a group or organization was formed"},
    "P749": {"label": "parent organization", "description": "parent organization or unit of an organization"},
    "P800": {"label": "notable work", "description": "notable scientific, artistic or literary work of the subject"},
    "P802": {"label": "student", "description": "notable student(s) of the subject individual"},
    "P921": {"label": "main subject", "description": "primary topic of a work or act of communication"},
    "P1038": {"label": "relative", "description": "family member (qualify with kinship to subject P1039)"},
    "P1082": {"label": "population", "description": "number of people inhabiting the place"},
    "P1142": {"label": "political ideology", "description": "political ideology of an organization or person"},
    "P1313": {"label": "office held by head of government", "description": "political office fulfilled by the head of government"},
    "P1344": {"label": "participant in", "description": "event in which a person or organization was a participant"},
    "P1387": {"label": "political alignment", "description": "political position within the left-right political spectrum"},
    "P1411": {"label": "nominated for", "description": "award nomination received by a person, organization or creative work"},
    "P1416": {"label": "affiliation", "description": "organization that a person is affiliated with"},
    "P1532": {"label": "country for sport", "description": "country a person or team represents when playing a sport"},
    "P1576": {"label": "lifestyle", "description": "typical way of life of an individual, group, or culture"},
    "P2044": {"label": "elevation above sea level", "description": "height of the item above a fixed reference point"},
    "P2046": {"label": "area", "description": "area of an entity"},
    "P3373": {"label": "sibling", "description": "the subject and the object have at least one common parent"},
    "P7937": {"label": "form of creative work", "description": "structure of a creative work"},
}
